version: '3.8'

services:
  analysis-service:
    build: ./analysis_service
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TENDERLY_API_KEY=${TENDERLY_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - RPC_URL=${RPC_URL}
      - SAFE_ADDRESS=${SAFE_ADDRESS}
      - OWNER_A_PRIVATE_KEY=${OWNER_A_PRIVATE_KEY}
      - ETHERSCAN_URL=${ETHERSCAN_URL}

  safe-service:
    build: ./safe_service
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TENDERLY_API_KEY=${TENDERLY_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - RPC_URL=${RPC_URL}
      - SAFE_ADDRESS=${SAFE_ADDRESS}
      - OWNER_A_PRIVATE_KEY=${OWNER_A_PRIVATE_KEY}
      - ETHERSCAN_URL=${ETHERSCAN_URL} 